### ISSUE TITLE
request to upload maven repository

### ISSUE THREAD

**Issue by Gwonwoo-Nam** [pschichtel/aws-s3-post-object-presigner#1]
I think this library is useful. Could you upload it to the Maven Repository so that it can be used in Clojure?

**Comment by pschichtel** [comment]
Yeah, I can do that. I'm kinda surprised I didn't already...

**Comment by pschichtel** [comment]
As I thought: https://repo1.maven.org/maven2/tel/schich/aws-s3-post-object-presigner/0.1.1/

**Comment by pschichtel** [comment]
https://github.com/pschichtel/aws-s3-post-object-presigner/commit/0662980804939163c368b8704d8b987e7d4b98cd adds a banner showing the latest version in maven central and links to the artifact.

**Comment by Gwonwoo-Nam** [comment]
I appreciate it, thank you!

**Comment by bakyeono** [comment]
素晴らしいです。
